<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite hostname="INNOWAVE-383" ignored="0" name="Default test" tests="4" failures="1" timestamp="27 dez 2019 16:57:43 GMT" time="72.167" errors="0">
  <testcase name="step01" time="16.9" classname="delivery01.soi_70.OrderCreation_For_MACD_OrderCreation"/>
  <testcase name="step02" time="13.361" classname="delivery01.soi_70.OrderCreation_For_MACD_OrderCreation"/>
  <testcase name="step03" time="7.937" classname="delivery01.soi_70.OrderCreation_For_MACD_OrderCreation"/>
  <testcase name="step04" time="20.545" classname="delivery01.soi_70.OrderCreation_For_MACD_OrderCreation">
    <failure type="java.lang.Exception" message="Test Failed on Step 4">
      <![CDATA[java.lang.Exception: Test Failed on Step 4
at delivery01.soi_70.OrderCreation_For_MACD_OrderCreation.step04(OrderCreation_For_MACD_OrderCreation.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.Exception: Validation Failed on Step 4
at delivery01.soi_70.OrderCreation_For_MACD_OrderCreation.step04(OrderCreation_For_MACD_OrderCreation.java:176)
... 25 more
]]>
    </failure>
  </testcase> <!-- step04 -->
</testsuite> <!-- Default test -->
=======
<testsuite hostname="INNOWAVE-429" ignored="0" tests="0" failures="0" timestamp="20 Dec 2019 12:51:38 GMT" time="6.169" errors="0">
</testsuite>
>>>>>>> branch 'master' of https://github.com/LMAchas/simpleOrdering
