<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="7" hostname="INNOWAVE-383" name="delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation" tests="8" failures="0" timestamp="06 mar 2020 13:52:26 GMT" time="41.930" errors="1">
  <testcase name="step04" time="0.000" classname="delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation">
    <skipped/>
  </testcase> <!-- step04 -->
  <testcase name="step02" time="0.000" classname="delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation">
    <skipped/>
  </testcase> <!-- step02 -->
  <testcase name="step06" time="0.000" classname="delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation">
    <skipped/>
  </testcase> <!-- step06 -->
  <testcase name="step05" time="0.000" classname="delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation">
    <skipped/>
  </testcase> <!-- step05 -->
  <testcase name="step07" time="0.000" classname="delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation">
    <skipped/>
  </testcase> <!-- step07 -->
  <testcase name="step01" time="41.930" classname="delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation">
    <error type="java.lang.Exception" message="Test Failed on Step 1">
      <![CDATA[java.lang.Exception: Test Failed on Step 1
at delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation.step01(SOI_721_TC03_PC_MACDOrder_OrderTypeValidation.java:149)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.Exception: Not possible to perform login on Partners Community
at delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation.step01(SOI_721_TC03_PC_MACDOrder_OrderTypeValidation.java:137)
... 25 more
]]>
    </error>
  </testcase> <!-- step01 -->
  <testcase name="step03" time="0.000" classname="delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation">
    <skipped/>
  </testcase> <!-- step03 -->
  <testcase name="step08" time="0.000" classname="delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation">
    <skipped/>
  </testcase> <!-- step08 -->
</testsuite> <!-- delivery01.soi_721.SOI_721_TC03_PC_MACDOrder_OrderTypeValidation -->
